---

dotfiles_devlog_enabled: True
dotfiles_default_editor: nvim
dotfiles_default_pager: vimpager
dotfiles_go_path: ~/go/

dotfiles_locale: en_US.UTF-8

dotfiles_git_pager: diff-so-fancy
dotfiles_git_editor: "{{ dotfiles_default_editor }}"

dotfiles_zsh_plugins:
  - git
  - ruby
  - git-flow
  - tmux
  - docker
  - docker-compose
  - docker-machine

dotfiles_files:
  - { name: 'agignore' }
  - { name: 'aliases' }
  - { name: 'ansible.cfg' }
  - { name: 'exports' }
  - { name: 'functions' }
  - { name: 'gitconfig' }
  - { name: 'gitignore' }
  - { name: 'screenrc' }
  - { name: 'tmux.conf' }
  - { name: 'vimrc' }
  - { name: 'zshrc' }
  - { name: 'direnvrc' }
  - { name: 'aria2.conf', destination: '~/.aria2/aria2.conf' }

dotfiles_git_name: "{{ dotfiles_user_name }}"
dotfiles_git_email: "{{ dotfiles_user_email }}"

dotfiles_sync_force: True

dotfiles_required_directories:
  - ~/.ansible/group_vars
  - ~/.ansible/host_vars
  - "{{ dotfiles_go_path }}"
  - ~/.vim/autoload
  - ~/.tmux/plugins
  - ~/.aria2
  - ~/.config/nvim
  - ~/.config/terminator
  - "{{ dotfiles_vimplug_destination | dirname }}"

dotfiles_required_files:
  - { path: '~/.ansible/hosts.ini', mode: '0600' }
  - { path: '~/.ssh/config', mode: '0600' }
  - { path: '~/.extra', mode: '0600' }

dotfile_apm_path: ~/.atom/packages
dotfiles_apm_packages:
  - sync-settings # Other packages and settings are pulled by this package

dotfiles_with_neovim: True
dotfiles_vimplug_destination: "{{ '~/.local/share/nvim/site/autoload/plug.vim' if dotfiles_with_neovim else '~/.vim/autoload/plug.vim' }}"
dotfiles_vim_executable: "{{ 'nvim' if dotfiles_with_neovim else 'vim' }}"

# Using the Maj key as it mimics Vim (forward|backward)-word shortcut.
# Also because Ctrl is used by macOS and Alt by Tmux
dotfiles_terminal_shortcuts:
  - sequence: ^[[1;2C
    action: forward-word
    comment: Maj + ->
  - sequence: ^[[1;2D
    action: backward-word
    comment: Maj + <-

dotfiles_install_atom_packages: True
dotfiles_install_tmux_packages: True
dotfiles_install_vim_packages: True
