---

osx_i18n:
  calendar: Calendrier

osx_languages:
  - fr
  - en

osx_locale: fr_FR@currency=EUR

brew_packages:
  - md5sha1sum # More checksum tools
  - coreutils # for things like realpath…
  - rclone # Cloud sync à-la rsync
  - caddy # Webserver/Reverse-Proxy/more…
  - fdupes # Duplicates file finder
  - devd # Local webserver for developers
  - watch # GNU watch command
  - forego # Foreman in Go
  - ag # Grep replacement
  - fzf # Command line fuzzy finder
  - diff-so-fancy # Differ
  - ssh-copy-id # Copy ssh keys to remote hosts
  - dockutil # Dock management from the command line

brew_cask_apps:
  - google-chrome # Default browser
  - appcleaner # For easy apps cleanup
  - iterm2 # Default terminal emulator
  - atom # Default code editor
  - launchbar # Spotlight replacement
  - keepassxc # Password manager
  - gpg-suite # GPG made easy (+ Mail.app extension)
  - slack # For team communications
  - spotify # Music ease the mind
  - lunchy # Launchctl wrapper
  - spectacle # Window manager
  - ngrok # Secure(?) tunneling
  - postman # HTTP requesting interface
  - fluid # Dedicated Mac app per website
  - typora # Useful markdown editor

removed_dock_items:
  - Launchpad
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences

added_dock_items:
  - name: Finder
    position: 1
  - name: Mail
    position: 2
  - name: "{{ osx_i18n['calendar'] }}"
    position: 3
  - name: iTerm
    path: "/Applications/iTerm.app"
    position: 4
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    position: 5
  - name: Spotify
    path: /Applications/Spotify.app
    position: 6
  - name: MacPass
    path: "/Applications/MacPass.app"
    position: 7
  - name: Atom
    path: /Applications/Atom.app
    position: 8
  - name: Slack
    path: /Applications/Slack.app
    position: 9

dock_icons_size: 36.0

launchbar_actions_directory: ~/Library/Application Support/LaunchBar/Actions
launchbar_actions:
  - filename: 'Spotify - Play:Pause.lbaction'
    url: https://github.com/mlinzner/LaunchBarActions/blob/master/actions/Control%20Spotify/packages/Spotify%20-%20Play:Pause.lbaction?raw=true
    checksum: 'sha256:a08d1bb667c6cec1089ac7dfd853c2a376e3d5269a8ad5e380cafe85526cb141'
  - filename: 'Spotify - Next Song.lbaction'
    url: https://github.com/mlinzner/LaunchBarActions/blob/master/actions/Control%20Spotify/packages/Spotify%20-%20Next%20Song.lbaction?raw=true
    checksum: 'sha256:e6e2ee949eafed06ea93baf58cdc36af8e84258fb01f6562b15f706cc1bd8c1a'
  - filename: 'Spotify - Previous Song.lbaction'
    url: https://github.com/mlinzner/LaunchBarActions/blob/master/actions/Control%20Spotify/packages/Spotify%20-%20Previous%20Song.lbaction?raw=true
    checksum: 'sha256:f4f3698b1bda0d40e893d00afb972248b20fa143a02cce91213325f068703d62'
  - filename: 'Caffeinate.lbaction'
    url: https://s3.amazonaws.com/renaghan/lbdist/Caffeinate.lbaction
    checksum: 'sha256:70c5d4512b95d89add73d698ed0fc194a46be9b6d559358ee6abce5810d512cc'
launchbar_plist_domain: at.obdev.LaunchBar
launchbar_configuration_file: ~/Library/Application Support/LaunchBar/Configuration.plist

go_get: []
