---

- name: Installing Golang
  apt:
    name: golang-go
    state: present
  when: dev_distribution == 'debian'
  become: true

- name: Installing Golang
  homebrew:
    name: go
    state: present
  when: dev_distribution == 'darwin'

- name: Go get
  command: "go get {{ go_pkg | quote }}"
  register: go_get_output
  changed_when: go_get_output.stdout | search('(download)')
  environment:
    GOPATH: "{{ dotfiles_go_path | expanduser }}"
  with_items: "{{ go_get }}"
  loop_control:
    loop_var: go_pkg
