---

- name: Add Golang ppa
  apt_repository:
    repo: ppa:gophers/archive
    state: present
  when: dev_distribution == 'debian'
  become: true

- name: Installing Golang
  apt:
    name: '{{ go_debian_pkg.name }}'
    state: present
    update_cache: yes
  when: dev_distribution == 'debian'
  become: true

- name: Making go binaries accessible
  file:
    src: '{{ go_debian_pkg.bin_dir }}/{{ item }}'
    dest: '/usr/bin/{{ item }}'
    state: link
  when: dev_distribution == 'debian'
  become: true
  with_items:
    - go
    - gofmt

- name: Installing Golang
  homebrew:
    name: go
    state: present
  when: dev_distribution == 'darwin'

- name: Go get
  command: "go get {{ go_pkg | quote }}"
  register: go_get_output
  changed_when: go_get_output.stdout is search('(download)')
  environment:
    GOPATH: "{{ dotfiles_go_path | expanduser }}"
  with_items: "{{ go_get }}"
  loop_control:
    loop_var: go_pkg
