---

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      sudo: required

language: python
python: "2.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask ; brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi

install:
  - pip install ansible

script:
  - ansible-playbook playbook.yml --syntax-check
  - ansible-playbook playbook.yml --become
