---

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: "2.7"
    - os: osx
      sudo: required
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask ; brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - sed -i.bak 's/become_ask_pass = True/become_ask_pass = False/g' ansible.cfg
  - mv host_vars/localhost/vars.yml.tpl host_vars/localhost/vars.yml

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ansible ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install ansible ; fi

script:
  - ansible-playbook playbook.yml --syntax-check
  - ansible-playbook playbook.yml --become
