---

- hosts: all
  vars:
    dev_distribution: "{{ ansible_os_family | lower }}"
  roles:
    - name: os-setup
      tags: os-setup
    - name: dotfiles
      tags: dotfiles
    - name: docker
      tags: docker
    - name: projects
      tags: projects
    - name: backup
      tags: backup
