---

# Images are pulled from Docker Hub or any public Docker registry
docker_images_to_pull: []

###################
# Debian specific #
###################

# Docker machine release version
docker_machine_version: v0.12.2

# Docker machine release filename
docker_machine_filename: docker-machine-linux-x86_64

# Release url to download from
docker_machine_url: "https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/{{ docker_machine_filename }}"

# Max time to wait for Docker Daemon
docker_daemon_waiting_time: 30

# Docker hypervisor process name on macOS, used to check if Docker is running
docker_running_process_name: com.docker.hyperkit # Using Docker Hypervisor

# Docker service name on Debian
docker_service_name: docker.service
