---

- name: Setup
  include: common/setup.yml

- name: Neovim installation
  include: common/neovim.yml
  when: dotfiles_with_neovim
  tags:
    - neovim

- name: Setting up apps packages
  include: common/packages.yml
  tags:
    - packages

- name: Customizing iTerm
  include: darwin/iterm.yml
  when: dev_distribution == 'darwin'
  tags:
    - iterm

- name: Packages for tmux
  include: darwin/tmux.yml
  when: dev_distribution == 'darwin'

- name: Customizing Terminator
  include: debian/terminator.yml
  when: dev_distribution == 'debian'
  tags:
    - terminator
