---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose # Docker dev with docker-compose.yml files
    - docker-machine # Manage Docker hosts
  become: true
