---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose # Docker dev with docker-compose.yml files
  become: true

# https://docs.docker.com/machine/install-machine/
- name: Download docker-machine
  get_url:
    url: "{{ docker_machine_url }}"
    dest: /usr/local/bin/docker-machine
    mode: 0755
  become: true

- name: Adding user "{{ ansible_user_id }}"
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true

- name: Reset ssh connection
  meta: reset_connection
  become: true
  ignore_errors: true
