---

- name: Fonts to install
  include: fonts.yml
  tags: fonts

- name: Apps to install
  include: apps.yml
  tags: apps

- name: OS settings
  include: settings.yml
  tags: settings

- name: Launchbar actions and settings
  include: launchbar.yml
  tags: launchbar
