---

# See https://www.learningosx.com/101-ways-to-tweak-os-x-using-terminal/ and
# https://www.defaults-write.com for more

######
# OS #
######

- name: Save to disk by default
  osx_defaults:
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
  notify: Refresh UI

- name: Disable apps quarantine
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
  notify: Refresh UI

- name: Disable auto-correct
  osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  notify: Refresh UI

- name: Require password immediately after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: integer
    value: 1
  notify: Refresh UI

- name: Require password immediately after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 0.0
  notify: Refresh UI

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
  notify: Refresh UI

- name: Avoid creating .DS_Store files on USB volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
  notify: Refresh UI

- name: Expand save panel by default
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
  notify: Refresh UI

- name: Automatically quit printer app once the print jobs complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value:  true
  notify: Refresh UI

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
  notify: Refresh UI

##########
# Finder #
##########

- name: Show all filename extensions
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true
  notify: Refresh UI

- name: Show status bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  notify: Refresh UI

- name: Show path bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  notify: Refresh UI

- name: When performing a search, search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    value: "SCcf"
  notify: Refresh UI

- name: Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  notify: Refresh UI

- name: Use list view in all Finder windows by default
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    value: "clmv"
  notify: Refresh UI

- name: Hide icons for external hard drives on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: false
  notify: Refresh UI

- name: Hide icons for hard drives on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: false
  notify: Refresh UI

- name: Hide icons for servers on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: false
  notify: Refresh UI

- name: Hide icons for removable media on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: false
  notify: Refresh UI

- name: Disable windows shadow in screen capture
  osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: boolean
    value: true
  notify: Refresh UI

########################
# Internationalization #
########################

- name: Setup os languages
  osx_defaults:
    key: AppleLanguages
    type: array
    value: "{{ osx_languages }}"
  notify: Refresh UI

- name: Setup keyboard language
  osx_defaults:
    key: AppleLocale
    value: "{{ osx_locale }}"
  notify: Refresh UI

- name: Setting measurement unit
  osx_defaults:
    key: AppleMeasurementUnits
    type: string
    value: Centimeters
  notify: Refresh UI

- name: Enabling metric units
  osx_defaults:
    key: AppleMetricUnits
    type: bool
    value: true
  notify: Refresh UI

########
# Dock #
########

- name: Remove all useless Dock items
  shell: dockutil --remove '{{ item }}' --no-restart
  ignore_errors: true
  with_items: osx_removed_dock_items
  notify: Restart Dock

- name: Check if the Dock items exist or add it
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}' --no-restart
  with_items: "{{ osx_added_dock_items }}"
  when: item.path is defined
  notify: Restart Dock

- name: Fix the Dock items order
  shell: dockutil --move '{{ item.name }}' --position {{ item.position }}
  with_items: "{{ osx_added_dock_items }}"
  notify: Restart Dock

- name: Auto-hide the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: bool
    value: true
  notify: Restart Dock

- name: Set the icon size of Dock items to X pixels
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: "{{ osx_dock_icons_size }}"
  notify: Restart Dock

- name: Automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify: Restart Dock

##########
# Spaces #
##########

- name: Disable Dashboard
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true
  notify: Refresh UI

- name: Don’t automatically rearrange Spaces based on most recent use
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
  notify: Refresh UI

##############
# Appearance #
##############

- name: Enable Dark mode
  osx_defaults:
    key: AppleInterfaceStyle
    value: Dark
  notify: Refresh UI

- name: Disable transparency
  osx_defaults:
    key: AppleEnableMenuBarTransparency
    type: bool
    value: false
  notify: Refresh UI

- name: Activate debug menu in Safari
  osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
    state: present
  notify: Refresh UI

#############
# App Store #
#############

- name: Enable the automatic update check
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: true
  notify: Refresh UI

- name: Check for software updates daily, not just once per week
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1
  notify: Refresh UI

- name: Download newly available updates in background
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    type: int
    value: 1
  notify: Refresh UI

- name: Install System data files & security updates
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: int
    value: 1
  notify: Refresh UI

########
# Apps #
########

- name: Use the system-native print preview dialog
  osx_defaults:
    domain: com.google.Chrome
    key: DisablePrintPreview
    type: bool
    value: true
  notify: Refresh UI

- name: Expand the print dialog by default
  osx_defaults:
    domain: com.google.Chrome
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true
  notify: Refresh UI
