---

# https://github.com/junegunn/fzf#using-git
- name: Clone fzf repository
  git:
    repo: https://github.com/junegunn/fzf.git
    dest:  ~/.fzf
    depth: 1
    update: no
  register: cloned_fzf

- name: Install fzf
  command: ~/.fzf/install --completion --key-bindings --no-zsh --64 --update-rc
  when: cloned_fzf.changed
