---

- name: Installing Neovim for macOS
  homebrew:
    name: neovim
    state: present
  when: dev_distribution == 'macosx'

- name: Add Neovim ppa on Ubuntu
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: dev_distribution == 'ubuntu'
  become: true

- name: Installing Neovim for Ubuntu
  apt:
    name: neovim
    state: present
  when: dev_distribution == 'ubuntu'
  become: true

- name: Symlinking .vimrc for Neovim
  file:
    src: ~/.vimrc
    dest: ~/.config/nvim/init.vim
    state: link
