---

- name: Dotfiles ▸ Installing Neovim for macOS
  homebrew:
    name: neovim
    state: present
  when: dev_distribution == 'macosx'

- name: Dotfiles ▸ Installing Neovim for Ubuntu
  apt:
    name: neovim
    state: present
  when: dev_distribution == 'ubuntu'

- name: Dotfiles ▸ Symlinking .vimrc for Neovim
  file:
    src: ~/.vimrc
    dest: ~/.config/nvim/init.vim
    state: link
