---

- name: Installing Atom packages
  include: apm.yml
  when: dotfiles_install_atom_packages

- name: Installing tmux packages
  include: tpm.yml
  when: dotfiles_install_tmux_packages

- name: Installing Vim packages
  include: vimplug.yml
  when: dotfiles_install_vim_packages
