---

########
# Tmux #
########

# https://github.com/tmux-plugins/tpm
- name: Getting tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    update: no
    version: master

- name: Installing tmux packages
  command: ~/.tmux/plugins/tpm/bin/install_plugins
