---

################
# VIM & Neovim #
################

# https://github.com/junegunn/vim-plug#installation
- name: Getting vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ dotfiles_vimplug_destination }}"

- name: Installing vim packages
  command: "{{ dotfiles_vim_executable | quote }} +PlugInstall +qall"
  changed_when: True # I can't find a way to detect changes with vim-plug so we expect changes each time
