---

##########
# VSCode #
##########

- name: Getting existing packages list
  command: "{{ dotfiles_vscode_app_name }} --list-extensions"
  changed_when: False
  register: vscode_packages_list

- name: VSCode packages installation
  command: "{{ dotfiles_vscode_app_name }} --install-extension {{ item | quote }}"
  when: not ansible_check_mode and item not in vscode_packages_list.stdout_lines
  with_items: "{{ dotfiles_vscode_packages }}"
