---

- name: Install Docker.app
  homebrew_cask:
    name: docker # Will also install docker-compose and docker-machine
    state: present
    accept_external_apps: True

- name: Checking if Docker is running
  shell: "pgrep {{ docker_running_process_name }} >/dev/null 2>&1"
  register: docker_status
  ignore_errors: yes
  changed_when: False

- name: Launching Docker daemon
  command: open /Applications/Docker.app
  register: docker_daemon_launched
  when: not ansible_check_mode and docker_status.rc > 0

- pause:
    seconds: "{{ docker_daemon_waiting_time }}"
    prompt: Waiting for Docker daemon
  when: not ansible_check_mode and docker_daemon_launched.changed
