---

- name: Create src folder
  file:
    path: "{{ projects_root }}"
    state: directory
    recurse: true

- name: Setting up projects
  include: setup-project.yml
  vars:
    project_directory: "{{ projects_root + '/' }}{{ (item.parent_directory + '/') if (item.parent_directory is defined) else '' }}{{ item.name }}"
    project: "{{ item }}"
  with_items: "{{ projects_list }}"
