---

- name: "Docker ▸ {{ ansible_distribution }} setup"
  include: "{{ dev_distribution }}/main.yml"
  tags:
    - docker

# Using apt for pip was triggering an ImportError
- name: Docker ▸ Install pip
  easy_install:
    name: pip
    state: present

# See https://docs.ansible.com/ansible/guide_docker.html#requirements
- name: Docker ▸ Add Ansible required pip packages
  pip:
    name: docker-compose
    state: present

- include: common/images-pull.yml
  tags:
    - docker
