---

- name: OSSetup ▸ Updating homebrew
  homebrew:
    update_homebrew: yes

- name: OSSetup ▸ Installing packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }} + {{ brew_packages }}"

- name: OSSetup ▸ Installing apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_apps }} + {{ brew_cask_apps }}"
