---

- name: Loading distribution's vars
  include_vars: "{{ dev_distribution }}.yml"
  tags:
    - always

- name: "{{ ansible_distribution }} Setup"
  include: "{{ dev_distribution }}/main.yml"

- name: Oh-My-Zsh setup
  include: zsh.yml
  tags:
    - apps
    - zsh
