---

github_release_regex: 'https:\/\/github\.com\/%s\/releases\/download\/[\d\w\.]{5,}\/[\w\.]+_%s\.\w+'

restic_repository: 'restic/restic'
restic_linux_binary_name: linux_amd64
restic_release_regex: "{{ github_release_regex | format((restic_repository | regex_escape), restic_linux_binary_name) }}"

restic_binary_dest: '/usr/local/bin/restic'

backup_scripts_directory: ~/restic-backup
backup_additional_exclusions: []
backup_cleanup: True
backup_cleanup_settings:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
backup_allow_prune: True
backup_with_cron: False
backup_cron:
  hour: "12,20"
  minute: "30"
